In [1]:
import torch 
import numpy as np

In [2]:
a = torch.tensor([1.0, 2.0, 3.0])
print(f"a = {a}, shape = {a.shape}, dtype = {a.dtype}")

a = tensor([1., 2., 3.]), shape = torch.Size([3]), dtype = torch.float32


In [3]:
np_array = np.array([4.0, 5.0, 6.0])
b = torch.from_numpy(np_array)
print(b)

tensor([4., 5., 6.], dtype=torch.float64)


In [4]:
x = torch.randn(3, 4)
y = torch.randn(3, 4)
print(x)
print(y)
print("Addition:", (x+y).shape)
print("Mutplication:", (x*y).shape)

tensor([[-0.6728,  1.2534,  0.9724, -1.1766],
        [ 0.1131, -0.4686,  1.2556,  0.3857],
        [ 0.1747,  1.6803,  0.4846, -0.2802]])
tensor([[-0.9941, -1.6440, -0.2012,  0.1369],
        [ 0.0603, -0.9351, -0.2940, -0.6460],
        [-1.0728,  0.9357, -1.5532, -1.4702]])
Addition: torch.Size([3, 4])
Mutplication: torch.Size([3, 4])


In [5]:
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C = A @ B
print(C)
print(C.shape)

tensor([[-0.7858,  0.3541, -1.8394,  0.0397, -0.1344],
        [-0.4061, -0.6366,  0.2150,  0.8739,  1.4726],
        [-1.0466,  1.2392,  0.4106,  1.8625,  1.3164]])
torch.Size([3, 5])


In [8]:
print(A)
v = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(f"Broadcasting: {A+ v}, shape: {(A+v).shape}")

tensor([[-0.5108,  0.4341,  0.1271, -0.1566],
        [-0.6173, -0.3577, -0.0378, -1.3728],
        [ 0.7027,  0.4101, -0.0727, -1.0494]])
Broadcasting: tensor([[0.4892, 2.4341, 3.1271, 3.8434],
        [0.3827, 1.6423, 2.9622, 2.6272],
        [1.7027, 2.4101, 2.9273, 2.9506]]), shape: torch.Size([3, 4])


In [13]:
t = torch.arange(12).float()
print(f"{t}, {t.shape}")
print(t.dtype)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]), torch.Size([12])
torch.float32


In [29]:
t2 = t.reshape(3, 4)
print(f"reshape(3, 4):\n {t2}")

reshape(3, 4):
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [25]:
t3 = t.reshape(2, 2, 3)
print(t3)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [26]:
print(f"First row: {t3[0]}")

First row: tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [27]:
print(t3[1, 0])

tensor([6., 7., 8.])


In [24]:
print(t3[1, 1])

tensor([ 9., 10., 11.])


In [30]:
print(t2)
print(t2[0])
print(t2[1, 2])
print(t2[:, 1])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([0., 1., 2., 3.])
tensor(6.)
tensor([1., 5., 9.])


In [31]:
print(t2[:, 1].shape)

torch.Size([3])


In [32]:
t4 = torch.randn(1, 3, 1)
print(t4.shape)

# 去掉所有size=1的维度
print(f"squeeze: {t4.squeeze().shape}")

# 在第0维加一个维度
print(f"unsqueeze(): {t2.unsqueeze(0).shape}")

torch.Size([1, 3, 1])
squeeze: torch.Size([3])
unsqueeze(): torch.Size([1, 3, 4])


In [36]:
# === Autograd: 自动求导 ===
x = torch.tensor(2.0, requires_grad = True)
f = x**2 + 3*x + 1
print(f"f(2) = {f.item()}")

f.backward()
print(f"f'(2) = {x.grad}")

f(2) = 11.0
f'(2) = 7.0


In [37]:
x = torch.randn(3, requires_grad = True)
print(x)
y = x * 2
z = y.mean()
z.backward()
print(x.grad)

tensor([-0.2529, -0.2478, -0.0217], requires_grad=True)
tensor([0.6667, 0.6667, 0.6667])


In [39]:
x = torch.randn(3, requires_grad = True)

for i in range(3):
    y = (x * 2).sum()
    y.backward()
    print(f"x.grad = {x.grad}")
    x.grad.zero_()

x.grad = tensor([2., 2., 2.])
x.grad = tensor([4., 4., 4.])
x.grad = tensor([6., 6., 6.])


In [40]:
x = torch.randn(3, requires_grad = True)
with torch.no_grad():
    y = x * 2
    print(y.requires_grad)

y = x.detach()
print(y.requires_grad)

False
False


In [41]:
import torch.nn as nn

In [42]:
linear = nn.Linear(4, 3)
print(f"Weight shape, {linear.weight.shape}")
print(f"Bias shape, {linear.bias.shape}")

x = torch.randn(2, 4)
output = linear(x)
print(f"output shape: {output.shape}")
print(output)

Weight shape, torch.Size([3, 4])
Bias shape, torch.Size([3])
output shape: torch.Size([2, 3])
tensor([[-0.7218,  0.3780, -0.8234],
        [ 0.6588,  1.2470, -0.6561]], grad_fn=<AddmmBackward0>)


In [44]:
class SimpleNet(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

model = SimpleNet(input_dim = 4, hidden_dim = 8, output_dim = 1)
print(model)
for name, param in model.named_parameters():
    print(f"{name}: {param.shape}")

x = torch.randn(5, 4)
output = model(x)
print(f"output shape: {output.shape}")

SimpleNet(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=8, out_features=1, bias=True)
)
fc1.weight: torch.Size([8, 4])
fc1.bias: torch.Size([8])
fc2.weight: torch.Size([1, 8])
fc2.bias: torch.Size([1])
output shape: torch.Size([5, 1])
